---
  - name: install zabbix repo
    yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm state=present
    tags:
     - zabbix-server

  - name: install mysql environment
    yum: name=mariadb-server state=latest
    tags:
     - zabbix-server
    notify:
     - restart-mysql

  - name: install zabbix-server-mysql
    yum: name=zabbix-server-mysql state=present
    tags:
     - zabbix-server

  - name: install zabbix-web-mysql
    yum: name=zabbix-web-mysql state=present
    tags:
     - zabbix-server

  - name: install the python mysqldb module
    yum: pkg=MySQL-python state=latest
    tags:
     - zabbix-server

  - name: enabel & restart mysql
    service: name=mariadb state=restarted
    tags:
     - zabbix-server

  - name: restart apache
    service: name=httpd state=restarted
    tags:
     - zabbix-server

  - name: MySQL | Create database
    mysql_db: name=zabbix state=present encoding=utf8 collation=utf8_bin
    tags:
     - zabbix-server

  - name: MySQL | Create database user
    mysql_user: name=zabbix_user password=123456  priv=zabbix.*:ALL state=present
    tags:
     - zabbix-server
    notify:
     - restart-mysql

  - name: reset Apache configuration file
    replace: dest=/etc/httpd/conf.d/zabbix.conf regexp='^# php_value date.timezone Europe/Riga' replace='php_value date.timezone Europe/Riga'

  - name: restart zabbix-server service
    service: name=zabbix-server state=restarted
    tags:
     - zabbix-server
